-- Show all records from the table
SELECT * FROM table1;

-- Total records from the table
SELECT count(*) FROM table1;

-- Count total sales by gender
SELECT gender, COUNT(total_sale) AS Total_Sales
FROM table1 
GROUP BY gender;

-- Sum total sales by category and gender, sorted by category
SELECT category, gender, SUM(total_sale) AS Total_Sales
FROM table1 
GROUP BY category, gender
ORDER BY category;

-- Find all rows containing any NULL values
SELECT *
FROM table1
WHERE transactions_id IS NULL
   OR sale_date IS NULL
   OR sale_time IS NULL
   OR customer_id IS NULL
   OR gender IS NULL
   OR age IS NULL
   OR category IS NULL
   OR quantity IS NULL
   OR price_per_unit IS NULL
   OR cogs IS NULL
   OR total_sale IS NULL;

-- Count how many rows have at least one NULL value
SELECT COUNT(*)
FROM table1
WHERE transactions_id IS NULL
   OR sale_date IS NULL
   OR sale_time IS NULL
   OR customer_id IS NULL
   OR gender IS NULL
   OR age IS NULL
   OR category IS NULL
   OR quantity IS NULL
   OR price_per_unit IS NULL
   OR cogs IS NULL
   OR total_sale IS NULL;

-- Calculate average age by gender (rounded)
SELECT gender, ROUND(AVG(age), 0) AS avg_age
FROM table1
GROUP BY gender;

-- Update NULL ages for male records with the male average
UPDATE table1
SET age = 41
WHERE gender = "male"
  AND age IS NULL;

-- Verify no male rows still have NULL age
SELECT *
FROM table1
WHERE gender = "male"
  AND age IS NULL;

-- Update NULL ages for female records with the female average
UPDATE table1
SET age = 41
WHERE gender = "female"
  AND age IS NULL;

-- Verify no female rows still have NULL age
SELECT *
FROM table1
WHERE gender = "female"
  AND age IS NULL;

-- Calculate average values for quantity, price_per_unit, cogs, and total_sale by category
SELECT category,
       ROUND(AVG(quantity), 2) AS avg_quantity,
       ROUND(AVG(price_per_unit), 2) AS avg_price_per_unit,
       ROUND(AVG(cogs), 2) AS avg_cogs,
       ROUND(AVG(total_sale), 2) AS avg_total_sale
FROM table1
GROUP BY category;

-- Fill NULL values for a specific category + gender with computed averages
UPDATE table1
SET quantity = 3,
    price_per_unit = 174,
    cogs = 91.86,
    total_sale = 444
WHERE category = "Clothing"
  AND gender = "Female"
  AND quantity IS NULL
  AND price_per_unit IS NULL
  AND cogs IS NULL
  AND total_sale IS NULL;
  
UPDATE table1
SET quantity = 3,
    price_per_unit = 185,
    total_sale = 469
WHERE category = "Clothing"
AND gender ="Female"
AND cogs = 91.86;


-- Level 1: Beginner
-- Q1: Retrieve all columns for sales made on the specific date '2022-02-02'.

SELECT * 
FROM table1
WHERE sale_date = "2022-02-02";

-- Q2: List all unique product categories available in the dataset.

SELECT DISTINCT category 
FROM table1;

-- Q3: Select all transactions where the total_sale is greater than 1000, ordered by value descending.

SELECT * 
FROM table1
WHERE total_sale >= 1000
ORDER BY total_sale DESC;

-- Q4: Find the total number of unique customers in the database.
SELECT  COUNT(DISTINCT customer_id) 
FROM table1;

-- Q5: Count the number of transactions made by each gender.
SELECT gender,COUNT(transactions_id) 
FROM table1
GROUP BY gender;

-- Q6: Write a query to display the transactions_id, the provided total_sale, and
-- a calculated column (quantity * price_per_unit) to verify data integrity.

SELECT transactions_id, total_sale, (quantity* price_per_unit) as total_sale
FROM table1;

-- Level 2: Intermediate
-- Q7: Calculate the total revenue (total_sale) generated by each product category.

SELECT gender, SUM(total_sale)
FROM table1
GROUP BY gender;

-- Q8: Find the average age of customers who purchased items from the 'Beauty' category.

SELECT category,AVG(age)
FROM table1
WHERE category = 'Beauty';

-- Q9: Extract the month name from the sale_date and calculate the total sales for each month.
SELECT MONTH(sale_date) as sale_month, SUM(total_sale) as total_revenue
FROM table1
GROUP BY MONTH(sale_date)
ORDER BY MONTH(sale_date);

-- With month Name.
SELECT DATE_FORMAT(sale_date, '%M') as sale_month,
	   SUM(total_sale) as total_revenue
FROM table1
GROUP BY sale_month;
-- ORDER BY sale_month;

-- Q10: Calculate the total Net Profit for each category (where Profit = total_sale - cogs).
SELECT category, ROUND(SUM(total_sale - cogs),2) AS net_sales
FROM table1
GROUP BY category;

-- Q11: Determine the peak shopping hours by counting the number of transactions for each hour of the day.
SELECT HOUR(sale_time) as peak_shopping_hour, COUNT(transactions_id) AS total_orders
FROM table1
GROUP BY sale_time
ORDER BY total_orders DESC;

-- Q12: Identify categories that have sold a total quantity of more than 1000 units using the HAVING clause.
SELECT category,SUM(quantity) AS total_quantity
FROM table1
GROUP BY category
HAVING total_quantity >= 1000;

-- Q13: Create a shift analysis by categorizing sales into 'Morning' (before 12 PM), 
-- 'Afternoon' (12 PM - 5 PM), and 'Evening' (after 5 PM). // Which part of the day (morning/afternoon/evening) has the most revenue?
SELECT 
CASE
WHEN  HOUR(sale_time) < 12 THEN "MORNING"
WHEN  HOUR(sale_time) BETWEEN 12 AND 17 THEN "AFTERNOOON"
ELSE "EVENING"
END AS shifts,
COUNT(*)  AS total_orders,
SUM(total_sale) AS total_revenue -- for most revenue
FROM table1
GROUP BY 1
ORDER BY 3 DESC;

-- Q14 Who are the top 5 customers by total spend?
SELECT 
	customer_id,
	SUM(total_sale) AS total_spend,
	COUNT(*) AS total_orders
FROM table1
GROUP BY customer_id 
ORDER BY 2 DESC 
LIMIT 5;

